### ISSUE TITLE
[Features]  Remember state option sidebar menu / Code available from Pull

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#1]
Hi @burdittw 

Can you add this feature to your fork
Remember state option to pushmenu/sidebar menu
The code is already available from https://github.com/ColorlibHQ/AdminLTE/pull/4131

**Comment by burdittw** [comment]
After playing around to add this feature, I ended up changing the SCSS and TS that handles the classes added to the menu if open, collapsed, or mini. With this I added the feature requested and it is saved to the localStorage of the browser.

**Comment by burdittw** [comment]
This update will be posted with fix, this issue is closed.
