### ISSUE TITLE
[Bug] Remember state vertical menu

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#10]
Hi,
There is a bug with remember state vertical menu when url have a #
https://github.com/ColorlibHQ/AdminLTE/pull/4131#issuecomment-1191579078

**Comment by burdittw** [comment]
I just tried this and do not see what you are describing. Can you maybe give a little more detail/code and a screenshot of what it is you see? I set in the example page the link to Widgets with the '#' in the href opened it and then refreshed the page with index.html# in the URL and it showed the same as it does without it.

![SidebarMenu](https://user-images.githubusercontent.com/10444699/180307921-67b22325-3287-4238-8634-35541e2190ad.png)

**Comment by lenamtl** [comment]
Hi,

I  think I was confused with the code that remember state is this only for toggle the menu mini / full/ close
and I thought this was also including some sort of the menu state when selecting a menu item based on url...

*My old code that remember menu selection was also present in my page and it has a probelm when # is in url.
