### ISSUE TITLE
This version does not work with Edge browser

### ISSUE THREAD

**Issue by zxo102** [burdittw/AdminLTE#14]
It works with chrome  but not with Edge browser (version 103.0.1264.71)

**Comment by lenamtl** [comment]
Hi, can you please elaborate what is not working?

**Comment by burdittw** [comment]
I test all the code in Edge so not sure what you mean it is not working. More info would need to be provided to try and fix anything that is not working on your side. Screenshots, code snippets, etc.

**Comment by zxo102** [comment]
It works now. Probably caused by Edge's cache(?) or my backend since I was playing different versions of adminLTE.  Thanks for your response @burdittw and  @lenamtl.
