### ISSUE TITLE
[CSS Dark] btn-tool border not enough visible

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#3]
In dark mode btn-tool border not enough visible to my opinion

**Comment by burdittw** [comment]
Yes, this was not a good look and feel as it was a quick example of how to add one. I have changed the code for this to be a Bootstrap card so that it can be changed using the Bootstrap framework. Update will be published soon.

**Comment by burdittw** [comment]
This update will be posted with fix, this issue is closed.
