### ISSUE TITLE
[CSS] CTA boxe adjustment

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#4]
The left menu box called "Your CTA button" need some padding at the bottom of the box, the button is to close from the browser UI to my opinion (note this may need to be test on other browser size).

**Comment by burdittw** [comment]
The CTA has been changed to a Bootstrap card and can now be modified using Bootstrap classes to work as you like.

**Comment by burdittw** [comment]
This update will be posted with fix, this issue is closed.
