### ISSUE TITLE
[CSS] Sidebar CSS and CSS map file

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#5]
Hi,

The class **sidebar-color-primary** is not present in CSS file but present in CSS map file...
`<nav class="sidebar sidebar-bg-dark sidebar-color-primary shadow sidebar-is-hover" data-theme="dark">`

**Comment by burdittw** [comment]
This issue is from the original project. My guess it was a carry-over from the v3 project. It is not being used so I have removed it from the sidebar in the classes that you listed. Update will be published soon.

**Comment by burdittw** [comment]
This update will be posted with fix, this issue is closed.
