### ISSUE TITLE
[CSS] Light form group label text is not visible

### ISSUE THREAD

**Issue by lenamtl** [burdittw/AdminLTE#6]
Hi,

On the form page / with light theme the form group label color is too light and text is not visible.
This seems a random issue maybe when switching from dark to light I will make more investigation.

**Comment by burdittw** [comment]
I was looking at the forms/general.html and don't see any issue. Is this the form you are talking about? Can you get a screenshot of the issue?

**Comment by lenamtl** [comment]
Hi,

This is a random issues, maybe this was related to the theme switcher because it was displaying the button and button label  colors from the dark theme on the light theme (but only for button group)
I could not reproduced it so I will close this for now.
